name: Dispatchable Workflow
permissions:
  contents: read
  issues: write 
on: 
  workflow_dispatch:
    inputs:
      runId:
        type: string
        required: true
        description: a unique runId for correlating workflows
jobs:
  stuff:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: gh issue create --title "I found a bug" --body "Nothing works"
